2022-04-07 17:57:55,515--test_case_ddt.py--INFO--45--用例--【登录成功】----执行成功
2022-04-07 17:57:55,551--test_case_ddt.py--INFO--45--用例--【账号或密码不正确】----执行成功
2022-04-07 17:57:55,624--test_case_ddt.py--ERROR--37--用例--【账号或密码不能为空】----执行失败
2022-04-07 17:57:55,624--test_case_ddt.py--ERROR--40--{'code': 1, 'msg': '账号或密码不能为空'} != {'code': 1, 'msg': '账号或密码不正确'}
- {'code': 1, 'msg': '账号或密码不能为空'}
?                           ^^^

+ {'code': 1, 'msg': '账号或密码不正确'}
?                           ^^
Traceback (most recent call last):
  File "D:\PycharmProjects\Python_C\python_35\demo\testcases\test_case_ddt.py", line 33, in test_login
    self.assertEqual(expected, result)
  File "D:\fc\anaconda3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "D:\fc\anaconda3\lib\unittest\case.py", line 1211, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "D:\fc\anaconda3\lib\unittest\case.py", line 753, in fail
    raise self.failureException(msg)
AssertionError: {'code': 1, 'msg': '账号或密码不能为空'} != {'code': 1, 'msg': '账号或密码不正确'}
- {'code': 1, 'msg': '账号或密码不能为空'}
?                           ^^^

+ {'code': 1, 'msg': '账号或密码不正确'}
?                           ^^

2022-04-07 17:57:55,699--test_case_ddt.py--ERROR--37--用例--【账号或密码不能为空】----执行失败
2022-04-07 17:57:55,699--test_case_ddt.py--ERROR--40--{'code': 1, 'msg': '账号或密码不能为空'} != {'code': 1, 'msg': '账号或密码不正确'}
- {'code': 1, 'msg': '账号或密码不能为空'}
?                           ^^^

+ {'code': 1, 'msg': '账号或密码不正确'}
?                           ^^
Traceback (most recent call last):
  File "D:\PycharmProjects\Python_C\python_35\demo\testcases\test_case_ddt.py", line 33, in test_login
    self.assertEqual(expected, result)
  File "D:\fc\anaconda3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "D:\fc\anaconda3\lib\unittest\case.py", line 1211, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "D:\fc\anaconda3\lib\unittest\case.py", line 753, in fail
    raise self.failureException(msg)
AssertionError: {'code': 1, 'msg': '账号或密码不能为空'} != {'code': 1, 'msg': '账号或密码不正确'}
- {'code': 1, 'msg': '账号或密码不能为空'}
?                           ^^^

+ {'code': 1, 'msg': '账号或密码不正确'}
?                           ^^

